

spring:
  datasource:
    url: jdbc:mysql://72.60.51.105:3306/onstreet_delivery?useSSL=false&createDataBaseIfNotExist=true
    username: root
    password: K0m0d031@Dr4g0n
  jpa:
    hibernate:
      ddl-auto: update